//! Ownership labels for managed stacks, and the `label_volumes` migration.
//!
//! Every `up` of a managed stack first regenerates [`ORCA_FILE`] next to the
//! compose file and passes it last (`-f`), so the user's compose file is never
//! edited. It labels every service, every network the project defines (not
//! external ones) and the top-level named volumes (see [`crate::labels`]).
//!
//! Labels on an existing volume cannot change, and compose versions that
//! stamp a config hash on volumes ask to recreate (losing data) one whose
//! declared labels differ. So a volume is labeled only when it does not exist
//! yet, and one that already carries orca's labels is declared with exactly
//! those. Existing unlabeled volumes are reported by coverage and
//! `docker.label_audit`, never relabeled.
//!
//! Networks have no data: labeling an existing compose network makes compose
//! recreate it once (with the containers on it, which the new service labels
//! recreate anyway).
//!
//! The file is JSON (valid YAML), so it can be read back: its `x-orca` key
//! records the anonymous volumes converted to named ones, which every
//! regeneration re-applies.
#![allow(clippy::disallowed_types)]

use std::collections::{BTreeMap, HashMap};
use std::path::Path;

use bollard::Docker;
use bollard::models::{ContainerSummary, VolumeCreateRequest};
use bollard::query_parameters::{
    ListContainersOptionsBuilder, ListVolumesOptions, RemoveVolumeOptionsBuilder,
};
use plugin_toolkit::anyhow::{self, Context, Result};
use plugin_toolkit::contract::BoxFuture;
use plugin_toolkit::contract::plan::PlannedChange;
use plugin_toolkit::schemars::JsonSchema;
use plugin_toolkit::serde::{Deserialize, Serialize};
use plugin_toolkit::serde_json::{self, Value};

use crate::Compose;
use crate::compose::ORCA_FILE;
use crate::compose_config::ComposeConfig;
use crate::labels::{self, Labels, OWNER_DOCKER};
use crate::prune::{COMPOSE_PROJECT_LABEL, COMPOSE_VOLUME_LABEL};
use crate::stacks::StackRow;
use crate::volume_coverage::HELPER_IMAGE;

pub const COMPOSE_SERVICE_LABEL: &str = "com.docker.compose.service";
pub const COMPOSE_ONEOFF_LABEL: &str = "com.docker.compose.oneoff";

const HEADER: &str = "# Generated by orca on every up: ownership labels and converted volumes.\n# Do not edit; it is rewritten. Remove it to stop orca's overrides.\n";

/// An anonymous volume of a service, converted to a named volume.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(crate = "plugin_toolkit::serde")]
#[schemars(crate = "plugin_toolkit::schemars")]
pub struct Conversion {
    pub service: String,
    /// The container path.
    pub target: String,
    /// The compose volume key.
    pub volume: String,
    /// The engine name, `<project>_<service>_<path-slug>`.
    pub name: String,
}

impl Conversion {
    pub fn new(project: &str, service: &str, target: &str) -> Self {
        let volume = format!("{service}_{}", slug(target));
        Self {
            service: service.to_string(),
            target: target.to_string(),
            name: format!("{project}_{volume}"),
            volume,
        }
    }

    /// `<service>:<target>`: what the plan lists and execute takes back.
    pub fn key(&self) -> String {
        format!("{}:{}", self.service, self.target)
    }
}

/// `/var/lib/app data` → `var_lib_app_data`.
pub fn slug(path: &str) -> String {
    let s: String = path
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() {
                c.to_ascii_lowercase()
            } else {
                '_'
            }
        })
        .collect();
    let s = s
        .split('_')
        .filter(|p| !p.is_empty())
        .collect::<Vec<_>>()
        .join("_");
    if s.is_empty() { "root".to_string() } else { s }
}

#[derive(Debug, Default, Serialize)]
#[serde(crate = "plugin_toolkit::serde")]
struct OrcaFile {
    services: BTreeMap<String, ServiceOverride>,
    #[serde(skip_serializing_if = "BTreeMap::is_empty")]
    networks: BTreeMap<String, LabelsOnly>,
    #[serde(skip_serializing_if = "BTreeMap::is_empty")]
    volumes: BTreeMap<String, VolumeOverride>,
    #[serde(rename = "x-orca")]
    x_orca: XOrca,
}

#[derive(Debug, Default, Serialize)]
#[serde(crate = "plugin_toolkit::serde")]
struct ServiceOverride {
    labels: BTreeMap<String, String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    volumes: Vec<MountOverride>,
}

#[derive(Debug, Serialize)]
#[serde(crate = "plugin_toolkit::serde")]
struct MountOverride {
    #[serde(rename = "type")]
    kind: &'static str,
    source: String,
    target: String,
}

#[derive(Debug, Serialize)]
#[serde(crate = "plugin_toolkit::serde")]
struct LabelsOnly {
    labels: BTreeMap<String, String>,
}

#[derive(Debug, Serialize)]
#[serde(crate = "plugin_toolkit::serde")]
struct VolumeOverride {
    #[serde(skip_serializing_if = "Option::is_none")]
    name: Option<String>,
    #[serde(skip_serializing_if = "BTreeMap::is_empty")]
    labels: BTreeMap<String, String>,
}

#[derive(Debug, Default, Serialize, Deserialize)]
#[serde(crate = "plugin_toolkit::serde")]
struct XOrca {
    #[serde(default)]
    conversions: Vec<Conversion>,
}

/// Labels of every engine volume, by name.
pub type EngineVolumes = HashMap<String, HashMap<String, String>>;

/// The labels to declare on a volume: `wanted` when it does not exist yet,
/// its own orca labels when orca already labeled it, else none (see the
/// module doc).
fn volume_labels(
    name: &str,
    wanted: BTreeMap<String, String>,
    engine: &EngineVolumes,
) -> BTreeMap<String, String> {
    match engine.get(name) {
        None => wanted,
        Some(have) if labels::is_managed(have.iter()) => have
            .iter()
            .filter(|(k, _)| k.starts_with("orca."))
            .map(|(k, v)| (k.clone(), v.clone()))
            .collect(),
        Some(_) => BTreeMap::new(),
    }
}

/// Conversions that still apply to `cfg` (the user's files): the service
/// still has an anonymous volume at that path. A path the user has since
/// bound or named is theirs again.
pub fn live_conversions(cfg: &ComposeConfig, conversions: &[Conversion]) -> Vec<Conversion> {
    conversions
        .iter()
        .filter(|c| {
            cfg.services.get(&c.service).is_some_and(|s| {
                s.volumes
                    .iter()
                    .any(|m| m.target == c.target && m.is_anonymous())
            })
        })
        .cloned()
        .collect()
}

/// The contents of [`ORCA_FILE`] for a stack whose user files resolve to
/// `cfg`. `stack` is the orca stack name (the unit id).
pub fn render(
    cfg: &ComposeConfig,
    stack: &str,
    conversions: &[Conversion],
    engine: &EngineVolumes,
) -> String {
    let project = cfg.name.as_str();
    let conversions = live_conversions(cfg, conversions);
    let mut file = OrcaFile::default();
    for svc in cfg.services.keys() {
        file.services.insert(
            svc.clone(),
            ServiceOverride {
                labels: Labels::for_(OWNER_DOCKER, project, Some(svc), Some(stack)).to_map(),
                volumes: conversions
                    .iter()
                    .filter(|c| &c.service == svc)
                    .map(|c| MountOverride {
                        kind: "volume",
                        source: c.volume.clone(),
                        target: c.target.clone(),
                    })
                    .collect(),
            },
        );
    }
    for (key, n) in &cfg.networks {
        if n.external == Some(true) {
            continue;
        }
        file.networks.insert(
            key.clone(),
            LabelsOnly {
                labels: Labels::for_(OWNER_DOCKER, project, None, Some(stack)).to_map(),
            },
        );
    }
    for (key, v) in &cfg.volumes {
        if v.external == Some(true) {
            continue;
        }
        let mounts: Vec<(&String, &String)> = cfg
            .services
            .iter()
            .flat_map(|(svc, s)| {
                s.volumes
                    .iter()
                    .filter(|m| m.named_volume() == Some(key))
                    .map(move |m| (svc, &m.target))
            })
            .collect();
        let mut wanted = Labels::for_(OWNER_DOCKER, project, None, Some(stack));
        if let [(svc, target)] = mounts.as_slice() {
            wanted = Labels::for_(OWNER_DOCKER, project, Some(svc), Some(stack)).with_mount(target);
        }
        let name = v.name.clone().unwrap_or_else(|| format!("{project}_{key}"));
        let labels = volume_labels(&name, wanted.to_map(), engine);
        if !labels.is_empty() {
            file.volumes
                .insert(key.clone(), VolumeOverride { name: None, labels });
        }
    }
    for c in &conversions {
        let wanted = Labels::for_(OWNER_DOCKER, project, Some(&c.service), Some(stack))
            .with_mount(&c.target)
            .to_map();
        file.volumes.insert(
            c.volume.clone(),
            VolumeOverride {
                name: Some(c.name.clone()),
                labels: volume_labels(&c.name, wanted, engine),
            },
        );
    }
    file.x_orca.conversions = conversions;
    let body = serde_json::to_string_pretty(&file).unwrap_or_default();
    format!("{HEADER}{body}\n")
}

/// The conversions recorded in an existing [`ORCA_FILE`]. A file that exists
/// but cannot be read fails: regenerating without its conversions would
/// silently swap converted volumes back to fresh anonymous ones.
pub fn read_conversions(dir: &Path) -> Result<Vec<Conversion>> {
    let path = dir.join(ORCA_FILE);
    let Ok(text) = std::fs::read_to_string(&path) else {
        return Ok(Vec::new());
    };
    let json: String = text
        .lines()
        .filter(|l| !l.trim_start().starts_with('#'))
        .collect::<Vec<_>>()
        .join("\n");
    let v: Value =
        serde_json::from_str(&json).with_context(|| format!("reading {}", path.display()))?;
    Ok(match v.get("x-orca") {
        Some(x) => {
            serde_json::from_value::<XOrca>(x.clone())
                .with_context(|| format!("reading x-orca in {}", path.display()))?
                .conversions
        }
        None => Vec::new(),
    })
}

/// Write `text` to `path` through a temp file and a rename; unchanged
/// content is not rewritten.
fn write_atomic(path: &Path, text: &str) -> Result<()> {
    if std::fs::read_to_string(path).is_ok_and(|old| old == text) {
        return Ok(());
    }
    let tmp = path.with_extension("yaml.orca-tmp");
    std::fs::write(&tmp, text).with_context(|| format!("writing {}", tmp.display()))?;
    std::fs::rename(&tmp, path).with_context(|| format!("replacing {}", path.display()))
}

pub async fn engine_volumes(docker: &Docker) -> Result<EngineVolumes> {
    Ok(docker
        .list_volumes(None::<ListVolumesOptions>)
        .await
        .map_err(|e| anyhow::anyhow!("list volumes: {e}"))?
        .volumes
        .unwrap_or_default()
        .into_iter()
        .map(|v| (v.name, v.labels))
        .collect())
}

/// Containers of `project`, running or stopped.
pub async fn project_containers(docker: &Docker, project: &str) -> Result<Vec<ContainerSummary>> {
    let filters = HashMap::from([("label", vec![format!("{COMPOSE_PROJECT_LABEL}={project}")])]);
    docker
        .list_containers(Some(
            ListContainersOptionsBuilder::new()
                .all(true)
                .filters(&filters)
                .build(),
        ))
        .await
        .map_err(|e| anyhow::anyhow!("list containers of {project}: {e}"))
}

/// The user's resolved config (without [`ORCA_FILE`]).
pub async fn user_config(row: &StackRow) -> Result<(Compose, ComposeConfig)> {
    let compose = row.compose()?.without_orca();
    let raw = compose.config_json().await?;
    Ok((compose, ComposeConfig::parse(&raw)?))
}

/// Regenerate [`ORCA_FILE`] with `conversions` (default: the ones it
/// records) and return the project with it passed last.
pub async fn write_with(
    row: &StackRow,
    docker: &Docker,
    conversions: Option<&[Conversion]>,
) -> Result<Compose> {
    let (compose, cfg) = user_config(row).await?;
    let recorded;
    let conversions = match conversions {
        Some(c) => c,
        None => {
            recorded = read_conversions(Path::new(&row.dir))?;
            &recorded
        }
    };
    let engine = engine_volumes(docker).await?;
    write_atomic(
        &Path::new(&row.dir).join(ORCA_FILE),
        &render(&cfg, &row.name, conversions, &engine),
    )?;
    Ok(compose.with_orca())
}

fn client() -> Result<&'static Docker> {
    crate::registration::adapter()
        .client()
        .map_err(|e| anyhow::anyhow!("{e}"))
}

/// Regenerate [`ORCA_FILE`] and return the project to run compose with.
pub async fn refresh(row: &StackRow) -> Result<Compose> {
    write_with(row, client()?, None).await
}

/// `compose up -d` (for `services`, or all) with a fresh [`ORCA_FILE`].
pub async fn up(row: &StackRow, services: &[&str]) -> Result<String> {
    Ok(refresh(row).await?.up(services).await?)
}

// ── anonymous volumes ───────────────────────────────────────────────────────

/// An anonymous volume of a stack service.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(crate = "plugin_toolkit::serde")]
#[schemars(crate = "plugin_toolkit::schemars")]
pub struct AnonymousVolume {
    pub service: String,
    pub target: String,
    /// The engine volumes behind it, one per container of the service.
    pub engine_names: Vec<String>,
}

fn service_containers<'a>(
    containers: &'a [ContainerSummary],
    service: &'a str,
) -> impl Iterator<Item = &'a ContainerSummary> {
    containers.iter().filter(move |c| {
        c.labels.as_ref().is_some_and(|l| {
            l.get(COMPOSE_SERVICE_LABEL).map(String::as_str) == Some(service)
                && l.get(COMPOSE_ONEOFF_LABEL).map(String::as_str) != Some("True")
        })
    })
}

/// Anonymous volume mounts of `cfg`, with the engine volume each service
/// container has there.
pub fn anonymous_volumes(
    cfg: &ComposeConfig,
    containers: &[ContainerSummary],
) -> Vec<AnonymousVolume> {
    let mut out = Vec::new();
    for (svc, s) in &cfg.services {
        for m in s.volumes.iter().filter(|m| m.is_anonymous()) {
            let engine_names = service_containers(containers, svc)
                .filter_map(|c| {
                    c.mounts.as_ref()?.iter().find_map(|mp| {
                        (mp.destination.as_deref() == Some(m.target.as_str()))
                            .then(|| mp.name.clone())
                            .flatten()
                    })
                })
                .collect();
            out.push(AnonymousVolume {
                service: svc.clone(),
                target: m.target.clone(),
                engine_names,
            });
        }
    }
    out
}

// ── label_volumes ───────────────────────────────────────────────────────────

/// One anonymous volume `label_volumes` would convert.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Planned {
    pub conversion: Conversion,
    /// The current anonymous volume; `None` when no container exists yet.
    pub old: Option<String>,
    /// Why it cannot be converted automatically.
    pub blocked: Option<String>,
}

/// The conversions for the anonymous volumes in `cfg` (the user's files)
/// that are not converted yet.
pub fn plan(
    cfg: &ComposeConfig,
    containers: &[ContainerSummary],
    converted: &[Conversion],
) -> Vec<Planned> {
    anonymous_volumes(cfg, containers)
        .into_iter()
        .filter(|a| {
            !converted
                .iter()
                .any(|c| c.service == a.service && c.target == a.target)
        })
        .map(|a| {
            let conversion = Conversion::new(&cfg.name, &a.service, &a.target);
            let (old, blocked) = match a.engine_names.as_slice() {
                [] => (None, None),
                [one] => (Some(one.clone()), None),
                many => (
                    None,
                    Some(format!(
                        "{} containers each hold their own volume here; convert by hand",
                        many.len()
                    )),
                ),
            };
            Planned {
                conversion,
                old,
                blocked,
            }
        })
        .collect()
}

pub fn planned_change(p: &Planned) -> PlannedChange {
    let c = &p.conversion;
    let detail = match (&p.blocked, &p.old) {
        (Some(why), _) => format!("not convertible: {why}"),
        (None, Some(old)) => format!(
            "stop '{}', copy {old} into new volume {} and verify it, declare it at {}, up, then remove {old} if no container uses it",
            c.service, c.name, c.target
        ),
        (None, None) => format!(
            "declare new volume {} at {} (no container yet, nothing to copy)",
            c.name, c.target
        ),
    };
    PlannedChange::new(c.key(), "convert").with_detail(detail)
}

/// The engine and compose steps of a migration. A seam so the sequencing and
/// its rollback are testable without a docker CLI.
pub trait Migrator: Send + Sync {
    fn stop<'a>(&'a self, service: &'a str) -> BoxFuture<'a, Result<()>>;
    fn start<'a>(&'a self, service: &'a str) -> BoxFuture<'a, Result<()>>;
    fn copy<'a>(&'a self, from: &'a str, to: &'a str) -> BoxFuture<'a, Result<()>>;
    /// A digest of every path's type, mode, owner, size and content.
    fn manifest<'a>(&'a self, volume: &'a str) -> BoxFuture<'a, Result<String>>;
    fn current_override(&self) -> Result<Option<String>>;
    fn write_override<'a>(&'a self, conversions: &'a [Conversion]) -> BoxFuture<'a, Result<()>>;
    fn restore_override(&self, previous: Option<&str>) -> Result<()>;
    fn up<'a>(&'a self, service: &'a str) -> BoxFuture<'a, Result<()>>;
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(crate = "plugin_toolkit::serde")]
#[schemars(crate = "plugin_toolkit::schemars")]
pub struct NotDone {
    pub item: String,
    pub reason: String,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(crate = "plugin_toolkit::serde")]
#[schemars(crate = "plugin_toolkit::schemars")]
pub struct Migrated {
    pub converted: Vec<String>,
    /// Old anonymous volumes removed after verification.
    pub removed: Vec<String>,
    /// Old volumes kept, and why.
    pub kept: Vec<NotDone>,
    pub skipped: Vec<NotDone>,
    pub failed: Vec<NotDone>,
}

/// Create the target volume with orca's labels, plus compose's project and
/// volume labels so compose adopts it as the stack's named volume.
pub async fn create_volume(
    docker: &Docker,
    project: &str,
    stack: &str,
    c: &Conversion,
) -> Result<()> {
    let mut labels: HashMap<String, String> =
        Labels::for_(OWNER_DOCKER, project, Some(&c.service), Some(stack))
            .with_mount(&c.target)
            .to_map()
            .into_iter()
            .collect();
    labels.insert(COMPOSE_PROJECT_LABEL.to_string(), project.to_string());
    labels.insert(COMPOSE_VOLUME_LABEL.to_string(), c.volume.clone());
    docker
        .create_volume(VolumeCreateRequest {
            name: Some(c.name.clone()),
            labels: Some(labels),
            ..Default::default()
        })
        .await
        .map_err(|e| anyhow::anyhow!("create volume {}: {e}", c.name))?;
    Ok(())
}

async fn volume_exists(docker: &Docker, name: &str) -> Result<bool> {
    match docker.inspect_volume(name).await {
        Ok(_) => Ok(true),
        Err(bollard::errors::Error::DockerResponseServerError {
            status_code: 404, ..
        }) => Ok(false),
        Err(e) => Err(anyhow::anyhow!("inspect volume {name}: {e}")),
    }
}

async fn referenced(docker: &Docker, volume: &str) -> Result<bool> {
    let filters = HashMap::from([("volume", vec![volume.to_string()])]);
    let users = docker
        .list_containers(Some(
            ListContainersOptionsBuilder::new()
                .all(true)
                .filters(&filters)
                .build(),
        ))
        .await
        .map_err(|e| anyhow::anyhow!("list containers using {volume}: {e}"))?;
    Ok(!users.is_empty())
}

async fn remove_volume(docker: &Docker, name: &str) -> Result<()> {
    docker
        .remove_volume(
            name,
            Some(RemoveVolumeOptionsBuilder::new().force(false).build()),
        )
        .await
        .map_err(|e| anyhow::anyhow!("remove volume {name}: {e}"))
}

/// Copy and verify one conversion into a volume this call creates. Returns
/// whether the target was created, so a failure can remove it.
async fn copy_one(
    docker: &Docker,
    m: &dyn Migrator,
    project: &str,
    stack: &str,
    p: &Planned,
    created: &mut Vec<String>,
) -> Result<()> {
    let c = &p.conversion;
    if volume_exists(docker, &c.name).await? {
        anyhow::bail!(
            "target volume {} already exists; remove it or convert by hand",
            c.name
        );
    }
    create_volume(docker, project, stack, c).await?;
    created.push(c.name.clone());
    if let Some(old) = &p.old {
        m.copy(old, &c.name).await?;
        let (want, got) = (m.manifest(old).await?, m.manifest(&c.name).await?);
        if want != got {
            anyhow::bail!(
                "verification failed: {} differs from {old} after the copy",
                c.name
            );
        }
    }
    Ok(())
}

/// Convert the confirmed `act` keys, one service at a time:
/// stop → create + copy + verify → declare in the override → up → remove
/// the old volume if no container references it. A failure before `up`
/// restores the previous override, removes the volumes it created and
/// starts the service again; the old volume is never touched.
pub async fn migrate(
    docker: &Docker,
    m: &dyn Migrator,
    project: &str,
    stack: &str,
    planned: &[Planned],
    act: &[String],
    converted: &[Conversion],
) -> Migrated {
    let mut out = Migrated::default();
    let mut by_service: BTreeMap<&str, Vec<&Planned>> = BTreeMap::new();
    for p in planned.iter().filter(|p| act.contains(&p.conversion.key())) {
        if let Some(why) = &p.blocked {
            out.skipped.push(NotDone {
                item: p.conversion.key(),
                reason: why.clone(),
            });
            continue;
        }
        by_service.entry(&p.conversion.service).or_default().push(p);
    }
    let mut conversions = converted.to_vec();
    for (svc, items) in by_service {
        let keys: Vec<String> = items.iter().map(|p| p.conversion.key()).collect();
        let fail = |out: &mut Migrated, reason: String| {
            out.failed.extend(keys.iter().map(|k| NotDone {
                item: k.clone(),
                reason: reason.clone(),
            }));
        };
        let previous = match m.current_override() {
            Ok(p) => p,
            Err(e) => {
                fail(&mut out, e.to_string());
                continue;
            }
        };
        let running = items.iter().any(|p| p.old.is_some());
        if running && let Err(e) = m.stop(svc).await {
            fail(&mut out, format!("stop: {e}"));
            if let Err(e) = m.start(svc).await {
                fail(&mut out, format!("start after failed stop: {e}"));
            }
            continue;
        }
        let mut created = Vec::new();
        let mut step: Result<()> = Ok(());
        for p in &items {
            step = copy_one(docker, m, project, stack, p, &mut created).await;
            if step.is_err() {
                break;
            }
        }
        if step.is_ok() {
            let mut next = conversions.clone();
            next.extend(items.iter().map(|p| p.conversion.clone()));
            step = m.write_override(&next).await;
            if step.is_ok() {
                conversions = next;
            }
        }
        if let Err(e) = step {
            let mut reason = e.to_string();
            if let Err(e) = m.restore_override(previous.as_deref()) {
                reason.push_str(&format!("; restoring the override failed: {e}"));
            }
            for name in &created {
                if let Err(e) = remove_volume(docker, name).await {
                    reason.push_str(&format!("; {e}"));
                }
            }
            if running && let Err(e) = m.start(svc).await {
                reason.push_str(&format!("; start: {e}"));
            }
            fail(&mut out, reason);
            continue;
        }
        if let Err(e) = m.up(svc).await {
            fail(
                &mut out,
                format!(
                    "up after the copy failed: {e}; the data is in the new volume, the old one is kept"
                ),
            );
            continue;
        }
        for p in items {
            out.converted.push(p.conversion.key());
            let Some(old) = &p.old else { continue };
            match referenced(docker, old).await {
                Ok(false) => match remove_volume(docker, old).await {
                    Ok(()) => out.removed.push(old.clone()),
                    Err(e) => out.kept.push(NotDone {
                        item: old.clone(),
                        reason: e.to_string(),
                    }),
                },
                Ok(true) => out.kept.push(NotDone {
                    item: old.clone(),
                    reason: "a container still references it".into(),
                }),
                Err(e) => out.kept.push(NotDone {
                    item: old.clone(),
                    reason: e.to_string(),
                }),
            }
        }
    }
    out
}

/// Builds the manifest inside the helper. `stat`/`find`/`sha256sum` are
/// busybox; paths are relative so source and target compare equal.
const MANIFEST_SCRIPT: &str = r#"set -eo pipefail; cd /v; { find . -exec stat -c '%n %F %a %u:%g' {} + | sort; find . -type f -exec stat -c '%n %s' {} + | sort; find . -type f -exec sha256sum {} + | sort -k2; } | sha256sum"#;

pub fn copy_args(from: &str, to: &str) -> Vec<String> {
    vec![
        "run".into(),
        "--rm".into(),
        "--network".into(),
        "none".into(),
        "--mount".into(),
        format!("type=volume,src={from},dst=/from,readonly"),
        "--mount".into(),
        format!("type=volume,src={to},dst=/to"),
        HELPER_IMAGE.into(),
        "sh".into(),
        "-c".into(),
        "cp -a /from/. /to/".into(),
    ]
}

pub fn manifest_args(volume: &str) -> Vec<String> {
    vec![
        "run".into(),
        "--rm".into(),
        "--network".into(),
        "none".into(),
        "--mount".into(),
        format!("type=volume,src={volume},dst=/v,readonly"),
        HELPER_IMAGE.into(),
        "sh".into(),
        "-c".into(),
        MANIFEST_SCRIPT.into(),
    ]
}

async fn docker_checked(args: &[String], what: &str) -> Result<String> {
    let mut cmd = plugin_toolkit::process::Command::new(crate::resolve_docker_bin()).args(args);
    if let Some(host) = crate::docker_host().await {
        cmd = cmd.env("DOCKER_HOST", host);
    }
    let out = cmd.output().await?;
    if !out.status.success {
        anyhow::bail!("{what}: {}", String::from_utf8_lossy(&out.stderr).trim());
    }
    Ok(String::from_utf8_lossy(&out.stdout).trim().to_string())
}

/// The real [`Migrator`]: compose for the service, helper containers for the
/// data.
pub struct ComposeMigrator<'a> {
    pub row: &'a StackRow,
    pub docker: &'a Docker,
}

impl Migrator for ComposeMigrator<'_> {
    fn stop<'a>(&'a self, service: &'a str) -> BoxFuture<'a, Result<()>> {
        Box::pin(async move {
            self.row.compose()?.stop(&[service]).await?;
            Ok(())
        })
    }
    fn start<'a>(&'a self, service: &'a str) -> BoxFuture<'a, Result<()>> {
        Box::pin(async move {
            self.row.compose()?.start(&[service]).await?;
            Ok(())
        })
    }
    fn copy<'a>(&'a self, from: &'a str, to: &'a str) -> BoxFuture<'a, Result<()>> {
        Box::pin(async move {
            docker_checked(&copy_args(from, to), &format!("copy {from} to {to}")).await?;
            Ok(())
        })
    }
    fn manifest<'a>(&'a self, volume: &'a str) -> BoxFuture<'a, Result<String>> {
        Box::pin(async move {
            let digest =
                docker_checked(&manifest_args(volume), &format!("manifest of {volume}")).await?;
            if digest.is_empty() {
                anyhow::bail!("manifest of {volume} is empty");
            }
            Ok(digest)
        })
    }
    fn current_override(&self) -> Result<Option<String>> {
        let path = Path::new(&self.row.dir).join(ORCA_FILE);
        match std::fs::read_to_string(&path) {
            Ok(s) => Ok(Some(s)),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(None),
            Err(e) => Err(anyhow::anyhow!("read {}: {e}", path.display())),
        }
    }
    fn write_override<'a>(&'a self, conversions: &'a [Conversion]) -> BoxFuture<'a, Result<()>> {
        Box::pin(async move {
            write_with(self.row, self.docker, Some(conversions)).await?;
            Ok(())
        })
    }
    fn restore_override(&self, previous: Option<&str>) -> Result<()> {
        let path = Path::new(&self.row.dir).join(ORCA_FILE);
        match previous {
            Some(text) => write_atomic(&path, text),
            None if path.exists() => {
                std::fs::remove_file(&path).with_context(|| format!("remove {}", path.display()))
            }
            None => Ok(()),
        }
    }
    fn up<'a>(&'a self, service: &'a str) -> BoxFuture<'a, Result<()>> {
        Box::pin(async move {
            up(self.row, &[service]).await?;
            Ok(())
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::compose_config::FIXTURE;
    use crate::test_engine::{FakeEngine, Route};
    use std::sync::Mutex;

    fn cfg() -> ComposeConfig {
        ComposeConfig::parse(FIXTURE).unwrap()
    }

    fn rendered(conversions: &[Conversion], engine: &EngineVolumes) -> Value {
        let text = render(&cfg(), "media-stack", conversions, engine);
        assert!(text.starts_with('#'));
        let json: String = text.lines().filter(|l| !l.starts_with('#')).collect();
        serde_json::from_str(&json).unwrap()
    }

    #[test]
    fn slug_flattens_a_path() {
        assert_eq!(slug("/var/lib/App Data/"), "var_lib_app_data");
        assert_eq!(slug("/"), "root");
        let c = Conversion::new("media", "app", "/cache");
        assert_eq!(
            (c.volume.as_str(), c.name.as_str()),
            ("app_cache", "media_app_cache")
        );
        assert_eq!(c.key(), "app:/cache");
    }

    #[test]
    fn render_labels_services_project_networks_and_new_volumes() {
        let v = rendered(&[], &EngineVolumes::new());
        let app = &v["services"]["app"]["labels"];
        assert_eq!(app[labels::MANAGED], "true");
        assert_eq!(app[labels::OWNER], "docker");
        assert_eq!(app[labels::STACK], "media");
        assert_eq!(app[labels::SERVICE], "app");
        assert_eq!(app[labels::UNIT], "media-stack");
        assert!(v["services"]["worker"]["labels"].is_object());
        assert_eq!(v["networks"]["default"]["labels"][labels::STACK], "media");
        assert!(v["networks"].get("proxy").is_none(), "external");
        assert!(
            v["networks"]["default"]["labels"]
                .get(labels::SERVICE)
                .is_none()
        );
        let data = &v["volumes"]["data"]["labels"];
        assert_eq!(data[labels::SERVICE], "app");
        assert_eq!(data[labels::MOUNT], "/data");
        assert!(v["volumes"].get("shared").is_none(), "external");
        assert!(v["services"]["app"].get("volumes").is_none());
    }

    #[test]
    fn existing_volumes_keep_their_labels() {
        let engine = EngineVolumes::from([
            (
                "media_data".to_string(),
                HashMap::from([(COMPOSE_PROJECT_LABEL.to_string(), "media".to_string())]),
            ),
            (
                "media_pg".to_string(),
                HashMap::from([
                    (labels::MANAGED.to_string(), "true".to_string()),
                    (labels::SERVICE.to_string(), "old-name".to_string()),
                    (COMPOSE_PROJECT_LABEL.to_string(), "media".to_string()),
                ]),
            ),
        ]);
        let v = rendered(&[], &engine);
        assert!(
            v["volumes"].get("data").is_none(),
            "unlabeled volumes are never relabeled"
        );
        let pg = v["volumes"]["pg"]["labels"].as_object().unwrap();
        assert_eq!(pg.len(), 2, "exactly its own orca labels: {pg:?}");
        assert_eq!(pg[labels::SERVICE], "old-name");
    }

    #[test]
    fn render_mounts_live_conversions_and_records_them() {
        let keep = Conversion::new("media", "app", "/cache");
        let stale = Conversion::new("media", "app", "/data");
        let gone = Conversion::new("media", "removed", "/x");
        let v = rendered(&[keep.clone(), stale, gone], &EngineVolumes::new());
        let mounts = v["services"]["app"]["volumes"].as_array().unwrap();
        assert_eq!(mounts.len(), 1);
        assert_eq!(mounts[0]["source"], "app_cache");
        assert_eq!(mounts[0]["target"], "/cache");
        assert_eq!(mounts[0]["type"], "volume");
        assert_eq!(v["volumes"]["app_cache"]["name"], "media_app_cache");
        assert_eq!(v["volumes"]["app_cache"]["labels"][labels::MOUNT], "/cache");
        assert!(v["services"].get("removed").is_none());
        let recorded: Vec<Conversion> =
            serde_json::from_value(v["x-orca"]["conversions"].clone()).unwrap();
        assert_eq!(recorded, vec![keep]);
    }

    #[test]
    fn conversions_read_back_and_an_unreadable_file_fails() {
        let dir = tempfile::tempdir().unwrap();
        assert!(read_conversions(dir.path()).unwrap().is_empty());
        let c = Conversion::new("media", "app", "/cache");
        std::fs::write(
            dir.path().join(ORCA_FILE),
            render(&cfg(), "m", std::slice::from_ref(&c), &EngineVolumes::new()),
        )
        .unwrap();
        assert_eq!(read_conversions(dir.path()).unwrap(), vec![c]);
        std::fs::write(dir.path().join(ORCA_FILE), "services: {}\n").unwrap();
        assert!(read_conversions(dir.path()).is_err());
    }

    fn container(name: &str, service: &str, mounts: &[(&str, &str)]) -> ContainerSummary {
        let mounts: Vec<String> = mounts
            .iter()
            .map(|(n, d)| format!(r#"{{"Name":"{n}","Destination":"{d}"}}"#))
            .collect();
        serde_json::from_str(&format!(
            r#"{{"Id":"{name}","Names":["/{name}"],"Labels":{{"{COMPOSE_SERVICE_LABEL}":"{service}"}},"Mounts":[{}]}}"#,
            mounts.join(",")
        ))
        .unwrap()
    }

    #[test]
    fn plan_finds_the_old_volume_and_blocks_replicas() {
        let containers = [container(
            "media-app-1",
            "app",
            &[("anon-cache", "/cache"), ("media_data", "/data")],
        )];
        let p = plan(&cfg(), &containers, &[]);
        assert_eq!(p.len(), 1);
        assert_eq!(p[0].conversion.key(), "app:/cache");
        assert_eq!(p[0].old.as_deref(), Some("anon-cache"));
        assert!(
            planned_change(&p[0])
                .detail
                .unwrap()
                .contains("copy anon-cache")
        );
        assert!(plan(&cfg(), &containers, &[p[0].conversion.clone()]).is_empty());
        let two = [
            container("media-app-1", "app", &[("a1", "/cache")]),
            container("media-app-2", "app", &[("a2", "/cache")]),
        ];
        let p = plan(&cfg(), &two, &[]);
        assert!(p[0].blocked.as_deref().unwrap().contains("2 containers"));
        assert!(plan(&cfg(), &[], &[])[0].old.is_none());
    }

    #[derive(Default)]
    struct FakeMigrator {
        calls: Mutex<Vec<String>>,
        bad_manifest: bool,
        written: Mutex<Option<Vec<Conversion>>>,
    }

    impl FakeMigrator {
        fn log(&self, s: String) {
            self.calls.lock().unwrap().push(s);
        }
        fn calls(&self) -> Vec<String> {
            self.calls.lock().unwrap().clone()
        }
    }

    impl Migrator for FakeMigrator {
        fn stop<'a>(&'a self, service: &'a str) -> BoxFuture<'a, Result<()>> {
            self.log(format!("stop {service}"));
            Box::pin(async { Ok(()) })
        }
        fn start<'a>(&'a self, service: &'a str) -> BoxFuture<'a, Result<()>> {
            self.log(format!("start {service}"));
            Box::pin(async { Ok(()) })
        }
        fn copy<'a>(&'a self, from: &'a str, to: &'a str) -> BoxFuture<'a, Result<()>> {
            self.log(format!("copy {from} {to}"));
            Box::pin(async { Ok(()) })
        }
        fn manifest<'a>(&'a self, volume: &'a str) -> BoxFuture<'a, Result<String>> {
            self.log(format!("manifest {volume}"));
            let digest = if self.bad_manifest {
                volume.to_string()
            } else {
                "same".into()
            };
            Box::pin(async move { Ok(digest) })
        }
        fn current_override(&self) -> Result<Option<String>> {
            Ok(Some("previous".into()))
        }
        fn write_override<'a>(
            &'a self,
            conversions: &'a [Conversion],
        ) -> BoxFuture<'a, Result<()>> {
            self.log("write".into());
            *self.written.lock().unwrap() = Some(conversions.to_vec());
            Box::pin(async { Ok(()) })
        }
        fn restore_override(&self, previous: Option<&str>) -> Result<()> {
            self.log(format!("restore {}", previous.unwrap_or("-")));
            Ok(())
        }
        fn up<'a>(&'a self, service: &'a str) -> BoxFuture<'a, Result<()>> {
            self.log(format!("up {service}"));
            Box::pin(async { Ok(()) })
        }
    }

    fn engine(extra: Vec<Route>) -> FakeEngine {
        let mut routes = extra;
        routes.extend([
            Route::new("GET", "/volumes/media_app_cache", 404, r#"{"message":"no such volume"}"#),
            Route::new("POST", "/volumes/create", 201, r#"{"Name":"media_app_cache","Driver":"local","Mountpoint":"","Labels":{},"Scope":"local","Options":{}}"#),
            Route::new("GET", "/containers/json", 200, "[]"),
            Route::new("DELETE", "/volumes/anon-cache", 204, ""),
            Route::new("DELETE", "/volumes/media_app_cache", 204, ""),
        ]);
        FakeEngine::routed(routes)
    }

    fn planned() -> Vec<Planned> {
        vec![Planned {
            conversion: Conversion::new("media", "app", "/cache"),
            old: Some("anon-cache".into()),
            blocked: None,
        }]
    }

    fn run(e: &FakeEngine, m: &FakeMigrator) -> Migrated {
        plugin_toolkit::reactor::block_on(migrate(
            &e.client(),
            m,
            "media",
            "media-stack",
            &planned(),
            &["app:/cache".to_string()],
            &[],
        ))
    }

    #[test]
    fn migrate_creates_a_labeled_volume_copies_verifies_and_removes_the_old_one() {
        let e = engine(vec![]);
        let m = FakeMigrator::default();
        let out = run(&e, &m);
        assert_eq!(out.converted, vec!["app:/cache"]);
        assert_eq!(out.removed, vec!["anon-cache"]);
        assert!(out.failed.is_empty(), "{out:?}");
        assert_eq!(
            m.calls(),
            vec![
                "stop app",
                "copy anon-cache media_app_cache",
                "manifest anon-cache",
                "manifest media_app_cache",
                "write",
                "up app"
            ]
        );
        assert_eq!(
            m.written.lock().unwrap().as_ref().unwrap()[0].name,
            "media_app_cache"
        );
        let body: Value = serde_json::from_str(&e.bodies("/volumes/create")[0]).unwrap();
        assert_eq!(body["Name"], "media_app_cache");
        let l = &body["Labels"];
        assert_eq!(l[labels::MANAGED], "true");
        assert_eq!(l[labels::OWNER], "docker");
        assert_eq!(l[labels::STACK], "media");
        assert_eq!(l[labels::SERVICE], "app");
        assert_eq!(l[labels::UNIT], "media-stack");
        assert_eq!(l[labels::MOUNT], "/cache");
        assert_eq!(l[COMPOSE_PROJECT_LABEL], "media");
        assert_eq!(l[COMPOSE_VOLUME_LABEL], "app_cache");
        // The old volume is checked for users right before removal.
        assert!(
            e.targets("GET")
                .iter()
                .any(|t| t.contains(r#""volume":["anon-cache"]"#)),
            "{:?}",
            e.targets("GET")
        );
    }

    #[test]
    fn a_failed_verification_rolls_back_and_keeps_the_old_volume() {
        let e = engine(vec![]);
        let m = FakeMigrator {
            bad_manifest: true,
            ..Default::default()
        };
        let out = run(&e, &m);
        assert!(out.converted.is_empty() && out.removed.is_empty());
        assert!(
            out.failed[0].reason.contains("verification failed"),
            "{out:?}"
        );
        let calls = m.calls();
        assert!(!calls.contains(&"write".to_string()) && !calls.contains(&"up app".to_string()));
        assert_eq!(calls[calls.len() - 2..], ["restore previous", "start app"]);
        let deletes = e.paths("DELETE");
        assert_eq!(deletes.len(), 1, "{deletes:?}");
        assert!(
            deletes[0].ends_with("/volumes/media_app_cache"),
            "only the new volume"
        );
    }

    #[test]
    fn an_old_volume_still_referenced_is_kept() {
        let e = engine(vec![
            Route::new(
                "GET",
                "/containers/json",
                200,
                r#"[{"Id":"x","Names":["/x"]}]"#,
            )
            .when_query(r#""volume""#),
        ]);
        let m = FakeMigrator::default();
        let out = run(&e, &m);
        assert_eq!(out.converted, vec!["app:/cache"]);
        assert!(out.removed.is_empty());
        assert!(out.kept[0].reason.contains("references it"));
        assert!(e.paths("DELETE").is_empty());
    }

    #[test]
    fn an_existing_target_volume_is_never_reused() {
        let e = engine(vec![Route::new(
            "GET",
            "/volumes/media_app_cache",
            200,
            r#"{"Name":"media_app_cache","Driver":"local","Mountpoint":"","Labels":{},"Scope":"local","Options":{}}"#,
        )]);
        let m = FakeMigrator::default();
        let out = run(&e, &m);
        assert!(out.failed[0].reason.contains("already exists"), "{out:?}");
        assert!(e.bodies("/volumes/create").is_empty());
        assert!(e.paths("DELETE").is_empty(), "neither volume is removed");
    }

    #[test]
    fn helper_commands_are_read_only_where_they_read() {
        let c = copy_args("old", "new");
        assert!(c.contains(&"type=volume,src=old,dst=/from,readonly".to_string()));
        assert!(c.contains(&"type=volume,src=new,dst=/to".to_string()));
        assert_eq!(c.last().unwrap(), "cp -a /from/. /to/");
        let m = manifest_args("v");
        assert!(m.contains(&"type=volume,src=v,dst=/v,readonly".to_string()));
        assert!(m.contains(&"none".to_string()));
        assert!(MANIFEST_SCRIPT.contains("sha256sum") && MANIFEST_SCRIPT.contains("%a %u:%g"));
    }
}
